- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - dotfiles-test
- name: Cloning .dotfiles
  become_user: "{{ ansible_env.SUDO_USER }}"
  ansible.builtin.git:
    repo: 'https://github.com/carlosvalle/dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: master
  tags:
    - install
    - dotfiles
    - dotfiles-test
- name: Stow dotfiles
  become_user: "{{ ansible_env.SUDO_USER }}"
  shell: cd $HOME/.dotfiles && ./ubuntu
  tags:
    - install
    - dotfiles
    - dotfiles-test
